config/routes.rb
Rails.application.routes.draw do
  resources :students
  root to: "students#index"
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    def index
    end
    def show
    end
    def add
    end
    def create
    end
    def edit
    end
    def update
    end
    def delete
    end
    def search
    end
    def result
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :get_student, only: [:edit, :update, :destroy, :show]
    def index
        @students = Student.all
    end

    def new 
        @student = Student.new
    end

    def create
        @student = Student.create(student_params)        
        redirect_to action: :index
    end

    def update
        @student.update(student_params)
        redirect_to action: :index
    end

    def destroy
        @student.destroy
        redirect_to action: :index
    end

####################################################

    def get_student
        @student = Student.find(params[:id])
    end

    def student_params
        params.require(:student).permit([:first_name, :last_name, :classroom])
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def icon_button
    @_controller.action_name == "edit" ? "<i class='fa fa-pencil'></i>&nbsp;&nbsp;Update".html_safe 
                                      : "<i class='fa fa-plus'></i>&nbsp;&nbsp;Add".html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HrdStudentRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main" class="container-fluid">
    <div class="row col-sm-11 center-block">
      <div class="col-sm-12 card form-horizontal">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/student/index.html.erb
this is index

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
<div class="col-sm-12 ">
  <div class="col-sm-8 center-block" style="margin-bottom: 40px;">
    <div class="form-group">
      <%= f.label :first_name, class: "col-sm-3"%>
      <%= content_tag :div, class: "col-sm-9" do %>
      <%= f.text_field :first_name, class: "form-control"%>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: "col-sm-3"%>
      <%= content_tag :div, class: "col-sm-9" do %>
      <%= f.text_field :last_name, class: "form-control"%>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :classroom, class: "col-sm-3"%>
      <%= content_tag :div, class: "col-sm-9" do %>
      <%= f.text_field :classroom, class: "form-control"%>
      <% end %>
    </div>
  </div>
  <%= f.button class: "btn btn-primary center-block", style: "width: 200px"  do%>
    <%=icon_button%>
  <%end%>
</div>
<%end%>

app/views/students/edit.html.erb
<h1>Editing <%=@student.first_name%> <%=@student.last_name%>
  <%= link_to(root_path, class: "btn pull-right") do %>
  <i class="fa fa-home fa-2x"></i>
  <%end%>
</h1>
<hr>

<%= render 'form' %>

app/views/students/index.html.erb
<h1>
  All Student
  <%= link_to(new_student_path, class: "btn pull-right") do %>
    <i class="fa fa-plus fa-2x"></i>
  <%end%>
  <%= link_to(root_path, class: "btn pull-right") do %>
    <i class="fa fa-search fa-2x"></i>
  <%end%>
</h1>
<hr>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="info">
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Classroom</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.classroom %></td>
        <td>
          <%= link_to "Show", student %>
          <%= link_to "Edit", edit_student_path(student) %>
          <%= link_to "Delete", student, method: :delete %>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<h1>Create a New Student
  <%= link_to(root_path, class: "btn pull-right") do %>
  <i class="fa fa-home fa-2x"></i>
  <%end%>
</h1>
<hr>

<%= render 'form' %>

app/views/students/show.html.erb
<h1>Show Student
  <%= link_to(root_path, class: "btn pull-right") do %>
  <i class="fa fa-home fa-2x"></i>
  <%end%>
</h1>
<hr>


<div class="col-sm-12 ">
  <div class="col-sm-8 center-block" style="margin-bottom: 40px;">
    <div class="form-group">
      <label class="col-sm-3">ID:</label>
      <div class="col-sm-9">
        <%= number_field_tag 'stu_id', @student.id, class: "form-control", 
        readonly: true %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3">First Name:</label>
      <div class="col-sm-9">
        <%= text_field_tag 'stu_first_name', @student.first_name, class: "form-control", 
        readonly: true %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3">Last Name:</label>
      <div class="col-sm-9">
        <%= text_field_tag 'stu_last_name', @student.last_name, class: "form-control", 
        readonly: true %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3">Classroom: </label>
      <div class="col-sm-9">
        <%= text_field_tag 'stu_classroom', @student.classroom, class: "form-control", 
        readonly: true %>
      </div>
    </div>
  </div>
  <%= link_to(edit_student_path(@student), class: "btn btn-primary center-block", style: "width: 200px") do %>
  <i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit
  <%end%>
</div>